version: '3.8'
services:
  pgdb:
    image: postgres:9.6.23-alpine3.14
    restart: always
    environment:
      POSTGRES_USER: $PGDB_USER
      POSTGRES_PASSWORD: $PGDB_PASSWORD
      POSTGRES_DB: $PGDB_NAME
    ports:
      - "${PGDB_PORT_LOCAL}:5432"
    volumes:
      - "C:/:/usr/local/share/postgresql"
      - db-data:/var/lib/postgresql/data

  app:
    build: Dockerfile
    env_file: ./.env.$NODE_ENV
    command:
      - node dist/index.js
    depends_on:
      - pgdb
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "${APP_PORT}:8080"

volumes:
  db-config:
  db-data:
